### ISSUE TITLE
update terminology in API documentation

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamDocumentationAPI#18]
Update the API documentation to use the latest terminology for the SlipStream resources.  Especially update "mutable" to "scalable".

**Comment by rbf** [comment]
This point was raised several times but not only for the API but for the whole codebase. When we eventually settle for the new terminology, we will need to completely refactor the code to use the updated wording.

**Comment by loomis** [comment]
Yes, but this ticket is just for the descriptions of the API, not refactoring the API itself.  This is so people can make the correspondance of what they see in the UI and advanced tutorial and the API.
