### ISSUE TITLE
update API examples to use cookie authentication

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamDocumentationAPI#28]
All of the examples in the documentation use basic authentication, which is no longer supported.  Update the examples to use cookie authentication.

**Comment by rbf** [comment]
+1 on this one: I had a request from somebody having problems while trying to follow the documentation steps on http://ssapi.sixsq.com/#basic-authentication.

**Comment by st** [comment]
- [x] update and review documentation
- [ ] `rake publish`
