### ISSUE TITLE
Update documentation API to latest version

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamDocumentationAPI#3]

**Comment by st** [comment]
- [x ] Document Event resource
- [ ] Update existing documentation (Java services)

**Comment by st** [comment]
* Take care of mutable deployment
* Pagination 
* public/private API ?

**Comment by schaubl** [comment]
@st : The API for the `/vms` resource has changed. 
See slipstream/SlipStreamServer#303 and slipstream/SlipStreamServer#281.

**Comment by st** [comment]
- [x] authentication
- [x] login
- [ ] Module
- [ ] VMs @schaubl is working on it
- [x] User
- [x] Event
- [ ] The new resource
- [x] Errors

**Comment by loomis** [comment]
Usage separated into separate ticket #11.
