### ISSUE TITLE
add link back to main documentation website

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamDocumentationAPI#4]
To improve the navigation between documentation websites and indexing on search engines, add a link from the API documentation back to the main documentation website (http://ssdocs.sixsq.com).

**Comment by loomis** [comment]
The change has been checked into the repository; however, it needs to be published.

**Comment by schaubl** [comment]
I will do it since I have to update the documentation API for slipstream/SlipStream#52.

**Comment by schaubl** [comment]
Done
